---
abstract: 'MapReduce UI is a web UI for MapReduce.'
author:
  - 'James Barton <james@revolet.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Deep: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: 'MapReduce UI'
no_index:
  directory:
    - inc
    - t
requires:
  Mojolicious: 0
  Redis::hiredis: 0
resources:
  license: http://opensource.org/licenses/mit-license.php
version: 0.13
